version: '2'

services:

  web:
    command: bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && uwsgi --ini uwsgi.ini"

  nginx:
    restart: always
    build: ./nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/static:/opt/static
      - /data/media:/opt/media
    links:
      - web
