version: '2.1'

services:

  redis:
    restart: always
    image: redis:3.2.6
    hostname: redis
    volumes:
      - redisdata:/data

  db:
    restart: always
    image: postgres:9.6.1
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    restart: always
    build: ./python
    hostname: web
    command: bash -c "./manage.py migrate && ./manage.py runserver_plus 0.0.0.0:8000"
    volumes:
      - ${SRC_DIR:-../src}:/opt/src
      - staticdata:/opt/static
      - mediadata:/opt/media
    working_dir:
      /opt/src
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "20"

  celery:
    restart: always
    build: ./python
    command: su -m docker -c "celery -A celeryconf:app worker -B --loglevel=INFO"
    volumes_from:
      - web
    working_dir:
      /opt/src
    links:
      - db
      - redis
    depends_on:
      - redis

volumes:
  redisdata:
  dbdata:
  mediadata:
  staticdata:
