version: '2.1'

services:

  redis:
    restart: always
    image: redis
    hostname: redis
    volumes:
      - redisdata:/data

  db:
    restart: always
    image: mysql:5.7
    hostname: db
    volumes:
      - dbdata:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project

  web:
    restart: always
    build: ./python
    hostname: web
    command: bash -c "./manage.py runserver_plus 0.0.0.0:8000"
    volumes:
      - ${SRC_DIR:-../src}:/opt/src
      - staticdata:/opt/static
      - mediadata:/opt/media
      - ${SRC_DIR:-../logging}:/opt/logging
    working_dir:
      /opt/src
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db

  celery:
    restart: always
    build: ./python
    hostname: celery
    command: su -m docker -c "celery -A celeryconf:app worker -B --loglevel=INFO"
    volumes_from:
      - web
    working_dir:
      /opt/src
    links:
      - db
      - redis
    depends_on:
      - redis

volumes:
  redisdata:
  dbdata:
  mediadata:
  staticdata:
